[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
build_flags = -DBOARD_HAS_PSRAM
lib_deps =
  mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display@^3.0.15
  adafruit/Adafruit GFX Library
  bitbank2/JPEGDEC
  bblanchon/ArduinoJson@^7